from __future__ import annotations

import logging

from clawagora.contracts.task import ExecutionArtifact, IntentClassification, IntakeEnvelope, Plan
from clawagora.cost import CostPolicy, estimate_cost_usd, estimate_tokens
from clawagora.providers.base import ModelProvider
from clawagora.prompts import PromptVersion, resolve_prompt

logger = logging.getLogger(__name__)


class Synthesizer:
    """Synthesis stage with optional LLM-enhanced conclusion.

    When *model* is provided, the conclusion field in the synthesis dict is
    generated by the model (more descriptive and context-aware).  Falls back
    to the deterministic template when the model returns ``None``.
    """

    def __init__(
        self,
        model: ModelProvider | None = None,
        *,
        cost_policy: CostPolicy | None = None,
    ) -> None:
        self._model = model
        self._cost_policy = cost_policy

    def synthesize(
        self,
        envelope: IntakeEnvelope,
        classification: IntentClassification,
        plan: Plan,
        artifacts: list[ExecutionArtifact],
    ) -> dict:
        return {
            "request_id": envelope.request_id,
            "intent": classification.model_dump(),
            "plan_id": plan.plan_id,
            "artifacts": [a.model_dump() for a in artifacts],
            "conclusion": self._conclusion(
                envelope, classification, artifacts, request_id=envelope.request_id
            ),
        }

    def _conclusion(
        self,
        envelope: IntakeEnvelope,
        classification: IntentClassification,
        artifacts: list[ExecutionArtifact],
        *,
        request_id: str,
    ) -> str:
        if not artifacts:
            return "No execution artifacts."
        forced = envelope.metadata.get("prompt_forced_versions")
        forced_map = forced if isinstance(forced, dict) else {}
        prompt_tpl = resolve_prompt(
            "synthesize.system",
            context_id=request_id,
            forced_versions=forced_map or None,
        )
        trace = dict(envelope.metadata.get("prompt_trace") or {})
        trace["synthesize"] = {"prompt_key": prompt_tpl.key, "prompt_version": prompt_tpl.version}
        envelope.metadata["prompt_trace"] = trace
        if self._model is not None:
            result = self._conclude_with_model(
                envelope,
                classification,
                artifacts,
                request_id=request_id,
                prompt_tpl=prompt_tpl,
            )
            if result:
                return result
        return self._conclude_deterministic(classification, artifacts)

    def _conclude_with_model(
        self,
        envelope: IntakeEnvelope,
        classification: IntentClassification,
        artifacts: list[ExecutionArtifact],
        *,
        request_id: str,
        prompt_tpl: PromptVersion,
    ) -> str | None:
        last_keys = list(artifacts[-1].output.keys())
        executors_run = [a.executor for a in artifacts]
        prompt = (
            f"Task intent: {classification.label} "
            f"(confidence {classification.confidence:.0%}).\n"
            f"Executors run: {executors_run}.\n"
            f"Last artifact keys: {last_keys}.\n"
            "State the outcome in one sentence."
        )
        raw = self._model.complete(  # type: ignore[union-attr]
            prompt,
            system=prompt_tpl.system,
            prompt_meta={"prompt_key": prompt_tpl.key, "prompt_version": prompt_tpl.version},
        )
        if raw and self._cost_policy is not None:
            policy = self._cost_policy
            combined_in = f"{prompt_tpl.system}\n{prompt}"
            tin = estimate_tokens(combined_in, token_chars_estimate=policy.token_chars_estimate)
            tout = estimate_tokens(raw.strip(), token_chars_estimate=policy.token_chars_estimate)
            est = estimate_cost_usd(tin, tout, policy=policy)
            usage = envelope.metadata.setdefault("llm_usage", [])
            usage.append(
                {
                    "prompt_key": prompt_tpl.key,
                    "prompt_version": prompt_tpl.version,
                    "est_cost_usd": est,
                }
            )
        return raw.strip() if raw else None

    def _conclude_deterministic(
        self,
        classification: IntentClassification,
        artifacts: list[ExecutionArtifact],
    ) -> str:
        last = artifacts[-1].output
        return (
            f"Completed pipeline for intent={classification.label}; last_keys={list(last.keys())}"
        )
