from django.urls import path

from orchestration.health import health
from orchestration.views import (
    CapabilityBundleDetailView,
    CapabilityBundleListView,
    GovernanceApplyRecommendationsView,
    GovernanceAlertSubscriptionsView,
    GovernanceAuditAnchorView,
    GovernanceApprovalTemplatesView,
    GovernanceBudgetForecastView,
    GovernanceLeaderboardHistoryView,
    GovernanceOrganizationUnitDetailView,
    GovernanceOrganizationUnitListView,
    GovernanceProfilesView,
    GovernanceDashboardView,
    GovernanceExecutorsView,
    GovernanceSubjectListView,
    GovernanceSummaryView,
    GovernanceDeadLetterReplayView,
    GovernanceDeadLettersView,
    GovernanceFeedbackView,
    GovernanceLeaderboardView,
    GovernanceRollbackView,
    GovernanceStatusView,
    OpenClawCallbackView,
    OpenClawDelegateTriggerView,
    OpenClawIntegrationStatusView,
    PolicyActivationLogListView,
    PolicyEvolutionProposalDetailView,
    PolicyEvolutionProposalListView,
    PolicyDraftActivateView,
    PolicyDraftDetailView,
    PolicyDraftListView,
    TaskAmendView,
    TaskApproveView,
    TaskCancelView,
    TaskCreateView,
    TaskDetailView,
    TaskInjectView,
    TaskReceiptView,
    TaskReplayView,
    TaskRejectView,
    TaskRetryView,
    TaskTimelineView,
    TaskVoteView,
    TaskVotesView,
)

urlpatterns = [
    path("v1/health/", health),
    path("v1/governance/apply-recommendations/", GovernanceApplyRecommendationsView.as_view()),
    path("v1/governance/alerts/subscriptions/", GovernanceAlertSubscriptionsView.as_view()),
    path("v1/governance/dead-letters/", GovernanceDeadLettersView.as_view()),
    path("v1/governance/dead-letters/replay/", GovernanceDeadLetterReplayView.as_view()),
    path("v1/governance/budget/forecast/", GovernanceBudgetForecastView.as_view()),
    path("v1/governance/leaderboard/history/", GovernanceLeaderboardHistoryView.as_view()),
    path("v1/governance/profiles/", GovernanceProfilesView.as_view()),
    path("v1/governance/dashboard/", GovernanceDashboardView.as_view()),
    path("v1/governance/summary/", GovernanceSummaryView.as_view()),
    path("v1/governance/executors/", GovernanceExecutorsView.as_view()),
    path("v1/governance/approval-templates/", GovernanceApprovalTemplatesView.as_view()),
    path("v1/governance/audit-anchor/", GovernanceAuditAnchorView.as_view()),
    path(
        "v1/governance/organization-units/<uuid:unit_id>/",
        GovernanceOrganizationUnitDetailView.as_view(),
    ),
    path("v1/governance/organization-units/", GovernanceOrganizationUnitListView.as_view()),
    path("v1/governance/subjects/", GovernanceSubjectListView.as_view()),
    path("v1/governance/feedback/", GovernanceFeedbackView.as_view()),
    path("v1/governance/leaderboard/", GovernanceLeaderboardView.as_view()),
    path("v1/governance/rollback/", GovernanceRollbackView.as_view()),
    path("v1/tasks/<uuid:task_id>/governance/", GovernanceStatusView.as_view()),
    # Task collection + creation
    path("v1/tasks/", TaskCreateView.as_view()),
    # Task instance
    path("v1/tasks/<uuid:task_id>/", TaskDetailView.as_view()),
    path("v1/tasks/<uuid:task_id>/retry/", TaskRetryView.as_view()),
    path("v1/tasks/<uuid:task_id>/amend/", TaskAmendView.as_view()),
    path(
        "v1/tasks/<uuid:task_id>/integrations/openclaw/delegate/",
        OpenClawDelegateTriggerView.as_view(),
    ),
    path("v1/tasks/<uuid:task_id>/timeline/", TaskTimelineView.as_view()),
    path("v1/tasks/<uuid:task_id>/receipt/", TaskReceiptView.as_view()),
    # Cancellation, forensic replay, approval flow, intervention
    path("v1/tasks/<uuid:task_id>/cancel/", TaskCancelView.as_view()),
    path("v1/tasks/<uuid:task_id>/replay/", TaskReplayView.as_view()),
    path("v1/tasks/<uuid:task_id>/approve/", TaskApproveView.as_view()),
    path("v1/tasks/<uuid:task_id>/reject/", TaskRejectView.as_view()),
    path("v1/tasks/<uuid:task_id>/inject/", TaskInjectView.as_view()),
    # Quorum voting — cast named votes; list all cast votes
    path("v1/tasks/<uuid:task_id>/vote/", TaskVoteView.as_view()),
    path("v1/tasks/<uuid:task_id>/votes/", TaskVotesView.as_view()),
    # Policy draft management + activation
    path("v1/policies/activation-log/", PolicyActivationLogListView.as_view()),
    path("v1/policies/proposals/", PolicyEvolutionProposalListView.as_view()),
    path(
        "v1/policies/proposals/<uuid:proposal_id>/",
        PolicyEvolutionProposalDetailView.as_view(),
    ),
    path("v1/policies/", PolicyDraftListView.as_view()),
    path("v1/policies/deactivate/", PolicyDraftActivateView.as_view()),
    path("v1/policies/<uuid:draft_id>/", PolicyDraftDetailView.as_view()),
    path("v1/policies/<uuid:draft_id>/activate/", PolicyDraftActivateView.as_view()),
    path("v1/capabilities/", CapabilityBundleListView.as_view()),
    path("v1/capabilities/<uuid:bundle_id>/", CapabilityBundleDetailView.as_view()),
    path("v1/integrations/openclaw/status/", OpenClawIntegrationStatusView.as_view()),
    path("v1/integrations/openclaw/callback/", OpenClawCallbackView.as_view()),
]
