# Generated by Django 6.0.3 on 2026-04-06 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("content", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                ("input_text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("classification", models.JSONField(blank=True, null=True)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("validation_reports", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("body", models.JSONField()),
                ("body_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="orchestration.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("phase", models.CharField(max_length=32)),
                ("kind", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orchestration.task",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "sequence"), name="uniq_task_event_sequence"
                    )
                ],
            },
        ),
    ]
