# Generated by Django 6.0.3 on 2026-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="error_detail",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="run_attempt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
