# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0002_task_idempotency_and_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "received"),
                    ("queued", "queued"),
                    ("running", "running"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                ],
                default="received",
                max_length=32,
            ),
        ),
    ]
