# Generated by Django 6.0.3 on 2026-04-06 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0003_task_cancelled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="policydraft",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "received"),
                    ("queued", "queued"),
                    ("running", "running"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("cancelled", "cancelled"),
                    ("pending_approval", "pending_approval"),
                ],
                default="received",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ticket_id", models.CharField(max_length=64)),
                ("risk_tier", models.CharField(max_length=16)),
                ("summary", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_request",
                        to="orchestration.task",
                    ),
                ),
            ],
        ),
    ]
