# Generated by Django 6.0.3 on 2026-04-07 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0004_governance_phase2"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="quorum",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ApprovalVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("voter_id", models.CharField(max_length=128)),
                (
                    "decision",
                    models.CharField(
                        choices=[("approve", "approve"), ("reject", "reject")], max_length=8
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="orchestration.approvalrequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("approval_request", "voter_id")},
            },
        ),
    ]
